services:
  - type: web
    name: quiz2-backend
    env: python
    rootDir: app/backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /api/
    envVars:
      - key: MONGO_URL
        sync: false
      - key: DB_NAME
        value: quiz_portal_db
      - key: CORS_ORIGINS
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_ALGO
        value: HS256
      - key: JWT_EXPIRE_HOURS
        value: "12"
      - key: GEMINI_API_KEY
        sync: false
      - key: HF_API_KEY
        sync: false
